export const layout = 'grid' // 布局 aside 、 head 、grid
export const server = 'http://192.168.3.214/web/api/' // 服务器地址
export const file = server + 'storage/app/uploads/' // 上传文件保存的路径
export const upfile = server + 'public/upload' // 上传文件
export const visualServer = server + 'public/visual'
export const visualAddServer = server + 'public/visual/add'
export const visualDelServer = server + 'public/visual/del/'
export const delfile = server + 'public/delfile/'
export const parentList = server + 'public/category/parent'
export const childList = server + 'public/category/child/'
export const addChild = server + 'public/category/add'
export const categoryEdit = server + 'public/category/edit/'
export const categoryDel = server + 'public/category/del/'
export const navigation = server + 'public/navigation'
